// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tradetrain;

import com.tradetrain.Candle;
import com.tradetrain.CandleDataOnDemand;
import com.tradetrain.CandleIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CandleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CandleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CandleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CandleIntegrationTest: @Transactional;
    
    @Autowired
    CandleDataOnDemand CandleIntegrationTest.dod;
    
    @Test
    public void CandleIntegrationTest.testCountCandles() {
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", dod.getRandomCandle());
        long count = Candle.countCandles();
        Assert.assertTrue("Counter for 'Candle' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CandleIntegrationTest.testFindCandle() {
        Candle obj = dod.getRandomCandle();
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Candle' failed to provide an identifier", id);
        obj = Candle.findCandle(id);
        Assert.assertNotNull("Find method for 'Candle' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Candle' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CandleIntegrationTest.testFindAllCandles() {
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", dod.getRandomCandle());
        long count = Candle.countCandles();
        Assert.assertTrue("Too expensive to perform a find all test for 'Candle', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Candle> result = Candle.findAllCandles();
        Assert.assertNotNull("Find all method for 'Candle' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Candle' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CandleIntegrationTest.testFindCandleEntries() {
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", dod.getRandomCandle());
        long count = Candle.countCandles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Candle> result = Candle.findCandleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Candle' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Candle' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CandleIntegrationTest.testFlush() {
        Candle obj = dod.getRandomCandle();
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Candle' failed to provide an identifier", id);
        obj = Candle.findCandle(id);
        Assert.assertNotNull("Find method for 'Candle' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCandle(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Candle' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CandleIntegrationTest.testMergeUpdate() {
        Candle obj = dod.getRandomCandle();
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Candle' failed to provide an identifier", id);
        obj = Candle.findCandle(id);
        boolean modified =  dod.modifyCandle(obj);
        Integer currentVersion = obj.getVersion();
        Candle merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Candle' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CandleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", dod.getRandomCandle());
        Candle obj = dod.getNewTransientCandle(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Candle' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Candle' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Candle' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CandleIntegrationTest.testRemove() {
        Candle obj = dod.getRandomCandle();
        Assert.assertNotNull("Data on demand for 'Candle' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Candle' failed to provide an identifier", id);
        obj = Candle.findCandle(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Candle' with identifier '" + id + "'", Candle.findCandle(id));
    }
    
}
