// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tradetrain;

import com.tradetrain.Candle;
import com.tradetrain.CandleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CandleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CandleDataOnDemand: @Component;
    
    private Random CandleDataOnDemand.rnd = new SecureRandom();
    
    private List<Candle> CandleDataOnDemand.data;
    
    public Candle CandleDataOnDemand.getNewTransientCandle(int index) {
        Candle obj = new Candle();
        setBeginDate(obj, index);
        setClosePrice(obj, index);
        setEndDate(obj, index);
        setMaxPrice(obj, index);
        setMinPrice(obj, index);
        setOpenPrice(obj, index);
        setVolume(obj, index);
        return obj;
    }
    
    public void CandleDataOnDemand.setBeginDate(Candle obj, int index) {
        Date beginDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setBeginDate(beginDate);
    }
    
    public void CandleDataOnDemand.setClosePrice(Candle obj, int index) {
        float closePrice = new Integer(index).floatValue();
        obj.setClosePrice(closePrice);
    }
    
    public void CandleDataOnDemand.setEndDate(Candle obj, int index) {
        Date endDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndDate(endDate);
    }
    
    public void CandleDataOnDemand.setMaxPrice(Candle obj, int index) {
        float maxPrice = new Integer(index).floatValue();
        obj.setMaxPrice(maxPrice);
    }
    
    public void CandleDataOnDemand.setMinPrice(Candle obj, int index) {
        float minPrice = new Integer(index).floatValue();
        obj.setMinPrice(minPrice);
    }
    
    public void CandleDataOnDemand.setOpenPrice(Candle obj, int index) {
        float openPrice = new Integer(index).floatValue();
        obj.setOpenPrice(openPrice);
    }
    
    public void CandleDataOnDemand.setVolume(Candle obj, int index) {
        int volume = index;
        obj.setVolume(volume);
    }
    
    public Candle CandleDataOnDemand.getSpecificCandle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Candle obj = data.get(index);
        Long id = obj.getId();
        return Candle.findCandle(id);
    }
    
    public Candle CandleDataOnDemand.getRandomCandle() {
        init();
        Candle obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Candle.findCandle(id);
    }
    
    public boolean CandleDataOnDemand.modifyCandle(Candle obj) {
        return false;
    }
    
    public void CandleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Candle.findCandleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Candle' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Candle>();
        for (int i = 0; i < 10; i++) {
            Candle obj = getNewTransientCandle(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
